DATA SEGMENT
    PORTA_1     EQU 00H
    PORTB_1     EQU 02H
    PORTC_1     EQU 04H
    PORT_CON_1  EQU 06H

    PORTA_2     EQU 08H
    PORTB_2     EQU 0AH
    PORTC_2     EQU 0CH
    PORT_CON_2  EQU 0EH  
    
    PORTA_3     EQU 10H
    PORTB_3     EQU 12H
    PORTC_3     EQU 14H
    PORT_CON_3  EQU 16H 
       
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA

START:
    MOV AX, DATA
    MOV DS, AX

    MOV DX, PORT_CON_1
    MOV AL, 10001010B
    OUT DX, AL
    
    MOV DX, PORT_CON_2
    MOV AL, 10001010B
    OUT DX, AL       
    
    MOV DX, PORT_CON_3
    MOV AL, 10001010B
    OUT DX, AL
    
MAIN_LOOP:
    CALL COUNT_DOOR
    MOV BL, AL

    MOV DX, PORTA_1
    IN AL, DX
    AND AL, 11110000B
    MOV AH, AL

    MOV AL, BL
    AND AL, 0000111B
    OR AL, AH
    OUT DX, AL  
    
    CMP BL, 6
    JE  SET_GREEN
    CMP BL, 3
    JAE SET_YELLOW
    JMP SET_RED

SET_GREEN:
    MOV DX, PORTA_1
    IN AL, DX
    AND AL, 00011111B
    OR AL, 01000000B
    OUT DX, AL
    JMP TEMP_CHECK

SET_YELLOW:
    MOV DX, PORTA_1
    IN AL, DX
    AND AL, 00011111B
    OR AL, 10000000B
    OUT DX, AL
    JMP TEMP_CHECK

SET_RED:
    MOV DX, PORTA_1
    IN AL, DX
    AND AL, 00011111B
    OR AL, 00100000B
    OUT DX, AL    


TEMP_CHECK:
    CALL DELAY

    MOV DX, PORTC_2
    IN AL, DX
    
    CMP AL, 17
    JBE MODE0_LED
    CMP AL, 18
    JE MODE1_LED
    CMP AL, 19
    JE MODE2_LED
    CMP AL, 20
    JE MODE3_LED
    CMP AL, 21
    JAE MODE4_LED
    JMP HEARTBEAT   

MODE0_LED:
    MOV DX, PORTA_2
    MOV AL, 00000001B
    OUT DX, AL
    JMP HEARTBEAT

MODE1_LED:
    MOV DX, PORTA_2
    MOV AL, 00000010B
    OUT DX, AL
    JMP HEARTBEAT

MODE2_LED:
    MOV DX, PORTA_2
    MOV AL, 00000100B
    OUT DX, AL
    JMP HEARTBEAT

MODE3_LED:
    MOV DX, PORTA_2
    MOV AL, 00001000B
    OUT DX, AL
    JMP HEARTBEAT

MODE4_LED:
    MOV DX, PORTA_2
    MOV AL, 00010000B
    OUT DX, AL

HEARTBEAT:       
        
    MOV DX, PORTB_2  
    IN AL, DX
                      
    CMP AL,  80H
    JB CRITICAL_ALERT 
    
    CMP AL,  99H
    JB LOW_ALERT
    
    MOV DX, PORTA_3 
    IN AL, DX
    AND AL, 11111100B
    OUT DX, AL
    JMP POWER
                                    
LOW_ALERT:
    MOV DX, PORTA_3
    IN AL, DX
    AND AL, 11111110B
    or al,00000001B
    OUT DX, AL

    JMP POWER 
                                    
CRITICAL_ALERT:
    MOV DX, PORTA_3
    IN AL, DX
    AND AL, 11111110B
    or al,00000010B
    OUT DX, AL

    JMP POWER
    
    
POWER:      
    MOV DX, PORTB_3  
    IN AL, DX

    CMP AL,  03H
    JB OFF_A            
            
    CMP AL,  10H
    JB OFF_T            
            
    MOV DX, PORTA_3 
    IN AL, DX
    AND AL, 00111111B
    OUT DX, AL
    JMP MAIN_LOOP     
            
OFF_A:
    MOV DX, PORTA_3
    IN AL, DX
    AND AL, 01111111B
    OR AL,11000000B
    OUT DX, AL

    JMP MAIN_LOOP 
                                    
OFF_T:
    MOV DX, PORTA_3
    IN AL, DX
    AND AL, 00111111B
    or AL,01000000B
    OUT DX, AL

    JMP MAIN_LOOP
    
    
    
    
 
COUNT_DOOR PROC
    MOV DX, PORTB_1
    IN AL, DX
    MOV BL, 0
    MOV CX, 6
COUNT_LOOP:
    SHR AL, 1
    JNC SKIP
    INC BL
SKIP:
    LOOP COUNT_LOOP
    MOV AL, BL
    RET
COUNT_DOOR ENDP

DELAY PROC
    MOV CX, 0FFFFH
DELAY_LOOP:
    LOOP DELAY_LOOP
    RET
DELAY ENDP

CODE ENDS
END START